<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Gemini_Generated_Image_m2d2nbm2d2nbm2d2 (1).ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Gemini_Generated_Image_m2d2nbm2d2nbm2d2 (1).ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.OrTools" Version="9.15.6755" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Supabase" Version="1.6.0" />
  </ItemGroup>

</Project>
